name: secret
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #语言国际化
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.2
  intl: ^0.17.0
  #图标
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0 #svg
  #状态管理
  provider: ^5.0.0
  collection: ^1.15.0
  package_info_plus: ^1.0.3 #包信息
  fl_chart: ^0.36.2 #图形
  path_provider: ^2.0.2 #文件管理
  sqflite: ^2.0.0+3 #数据库管理
  path: ^1.8.0
#  my_package:
#    path: ../my_package
#  my_plugin:
#    path: ../my_plugin

  #配置文件读写,[todo]版本太高有问题
  shared_preferences: ^2.0.0

  #工具类
  #flustars: ^2.0.1
  flutter_screenutil: ^5.0.0+2
  #json转models
  json_annotation: ^4.0.1
  #弹框组件，不依赖context
  flutter_smart_dialog: ^2.1.6
#  #web组件
  webview_flutter: ^2.0.8
#  flutter_webview_plugin: ^0.4.0
  #全局消息处理器
  rxdart: ^0.27.1
  #权限管理
  permission_handler: ^8.1.1
  #网络通信
  dio: ^4.0.0
  #提示信息
  fluttertoast: ^8.0.7
analyzer:
    enable-experiment:
    - non-nullable
    -
dev_dependencies:
  flutter_test:
    sdk: flutter
  #语言国际化
  #intl_translation: ^0.16.1
  #json转models
  build_runner: ^2.0.4
  json_serializable: ^4.1.3

flutter:
  uses-material-design: true
  #国际化
  generate: true # 添加这一行
  assets:
    - images/init_logo.webp
    - images/init_icon.png

    - images/login/syn.webp
    - images/login/qq.webp
    - images/login/wx.webp
    - images/login/weibo.webp
    - images/login/close.webp
    - images/login/safe.webp
    - images/login/member.webp
    - images/login/lock.webp

    - images/home/tab_1.png
    - images/home/tab_1s.png
    - images/home/tab_2.png
    - images/home/tab_2s.png
    - images/home/tab_3.png
    - images/home/tab_3s.png
    - images/home/tab_4.png
    - images/home/tab_4s.png